package fr.cm.scorexpress.core.model;

public enum ConfigType {
    RESULTATS,
    RESULTATS_INTER,
    PENALITY,
    DOSSARD_PARTICIPANTS,
    PARTICIPANTS,
    RESULTATS_EXPERT,
    RESULTATS_EXPERT_INTER,

    BALISES,
    CHRONOS,
    INFOSPORTIDENTS,
    IMPORT_PARTICIPANTS,
    DOSSARD_TEAMS,
    ETAPES,
    TEAMS
}
